### ISSUE TITLE
Graceful exit

### ISSUE THREAD

**Issue by YellowSloth** [LinuxMercedes/markovirc#24]
It would be nice that a ctrl-c would stop the program gracefully, not showing the error you currently see as you exit it.

Basically what is referenced here: https://stackoverflow.com/questions/2089421/capturing-ctrl-c-in-ruby

Also gives you the time to check irc is disconnected properly (perhaps an exit message referencing the bot) and make sure you haven't got any database things going on.

**Comment by brhoades** [comment]
I've implemented some simple ctrl+c handlers for both test_processing and marko itself. There's no custom quit message, but I'm pretty sure that's an issue with cinch itself. If this is something you desire, open an issue upstream with: https://github.com/cinchrb/cinch

I'm closing this as I don't plan to expand on this further--- this can't get much cleaner.
